web_emulations:
  iphone_15:
    viewport: { width: 430, height: 932 }
    device_scale_factor: 3
    is_mobile: true
    has_touch: true
    user_agent: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X)"
  pixel_7:
    viewport: { width: 412, height: 915 }
    device_scale_factor: 2.625
    is_mobile: true
    has_touch: true