app:
  base_url: "https://noovoleum.com"
  api_base: "https://noovoleum.com"  # Using site endpoints as placeholders
  default_user:
    username: ${USER_EMAIL}
    password: ${USER_PASSWORD}

playwright:
  browser: chromium
  headless: true
  video: only-on-failure
  screenshot: only-on-failure
  storage_state_path: ".auth/storage_state.json"

timeouts:
  short: 3
  medium: 10
  long: 30

mobile:
  android:
    app_path: "apps/android/app-release.apk"
    device_name: "Pixel_7_API_34"
    platformVersion: "14.0"
  ios:
    app_path: "apps/ios/App.app"
    device_name: "iPhone 15"
    platformVersion: "17.5"

perf:
  users: 50
  spawn_rate: 5
  run_time: "5m"
