name: Pipeline Tests

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          pip install -U pip
          pip install pytest pytest-asyncio pytest-xdist pytest-rerunfailures allure-pytest pyyaml playwright httpx pydantic pydantic-settings locust Appium-Python-Client
          python -c "import playwright; import asyncio; from playwright._impl._driver import compute_driver_executable; print('OK')"
          playwright install --with-deps
      - name: Run web tests
        run: pytest tests/web -q -n auto --alluredir=allure-results
      - uses: actions/upload-artifact@v4
        with:
          name: allure-web
          path: allure-results

  mweb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          pip install -U pip
          pip install pytest pytest-asyncio pytest-xdist pytest-rerunfailures allure-pytest pyyaml playwright httpx
          playwright install --with-deps
      - name: Run mweb tests
        run: pytest tests/mweb -q --alluredir=allure-results
      - uses: actions/upload-artifact@v4
        with:
          name: allure-mweb
          path: allure-results

  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          pip install -U pip
          pip install pytest allure-pytest httpx pyyaml
      - name: Run API tests
        run: pytest tests/api -q --alluredir=allure-results
      - uses: actions/upload-artifact@v4
        with:
          name: allure-api
          path: allure-results

  perf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          pip install -U pip
          pip install locust allure-pytest
      - name: Run Locust headless
        run: |
          locust -f tests/performance/locustfile.py --headless -u 50 -r 10 -t 1m --csv=locust
          mkdir -p allure-results
          cp locust*csv allure-results/ || true
      - uses: actions/upload-artifact@v4
        with:
          name: allure-perf
          path: allure-results

  allure-merge-and-publish:
    needs: [web, mweb, api, perf]
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: merged
      - name: Merge results
        run: |
          mkdir -p allure-results
          find merged -type f -name "*" -exec cp {} allure-results/ \;
      - name: Install Allure CLI
        run: |
          curl -sLo allure.tgz https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.29.0/allure-commandline-2.29.0.tgz
          tar -xzf allure.tgz
      - name: Generate report
        run: ./allure-2.29.0/bin/allure generate allure-results -o allure-report --clean
      - uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report
    environment:
      name: github-pages
    concurrency:
      group: "pages"
      cancel-in-progress: false
