name: Test Caller & Reporter

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      run_ui:
        description: 'Run UI suite'
        type: boolean
        default: true
      run_api:
        description: 'Run API suite'
        type: boolean
        default: true
      base_url:
        description: 'Base URL for UI suite'
        type: string
        default: 'https://noovoleum.com'
      browsers:
        description: 'UI browsers (comma-separated: chromium,firefox,webkit)'
        type: string
        default: 'chromium'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  meta:
    runs-on: ubuntu-latest
    outputs:
      event: ${{ steps.out.outputs.event }}
    steps:
      - id: out
        run: echo "event=${{ github.event_name }}" >> "$GITHUB_OUTPUT"

  ui:
    needs: meta
    # Run UI when:
    # - manual dispatch AND run_ui = true, OR
    # - any non-dispatch trigger (push/PR)
    if: ${{ (github.event_name == 'workflow_dispatch' && inputs.run_ui) || (github.event_name != 'workflow_dispatch') }}
    uses: ./.github/workflows/ui-test.yml
    with:
      base_url: ${{ github.event_name == 'workflow_dispatch' && inputs.base_url || 'https://noovoleum.com' }}
      browsers:  ${{ github.event_name == 'workflow_dispatch' && inputs.browsers  || 'chromium' }}

  api:
    needs: meta
    # Run API when:
    # - manual dispatch AND run_api = true, OR
    # - any non-dispatch trigger (push/PR)
    if: ${{ (github.event_name == 'workflow_dispatch' && inputs.run_api) || (github.event_name != 'workflow_dispatch') }}
    uses: ./.github/workflows/api-test.yml

  publish:
    runs-on: ubuntu-latest
    needs: [ui, api]
    if: always()
    steps:
      - name: Download UI artifacts (chromium)
        uses: actions/download-artifact@v4
        with:
          name: allure-ui-chromium
          path: ./allure-results/ui/chromium
        continue-on-error: true

      - name: Download UI artifacts (firefox)
        uses: actions/download-artifact@v4
        with:
          name: allure-ui-firefox
          path: ./allure-results/ui/firefox
        continue-on-error: true

      - name: Download UI artifacts (webkit)
        uses: actions/download-artifact@v4
        with:
          name: allure-ui-webkit
          path: ./allure-results/ui/webkit
        continue-on-error: true

      - name: Download API artifacts
        uses: actions/download-artifact@v4
        with:
          name: allure-api
          path: ./allure-results/api
        continue-on-error: true

      - name: Check for any Allure results
        id: check
        run: |
          shopt -s nullglob
          count=$(find ./allure-results -type f 2>/dev/null | wc -l || echo 0)
          if [ "$count" -gt 0 ]; then
            echo "has_results=true" >> $GITHUB_OUTPUT
          else
            echo "has_results=false" >> $GITHUB_OUTPUT
          fi

      - name: Merge Allure results
        if: steps.check.outputs.has_results == 'true'
        run: |
          mkdir -p ./allure-merged
          cp -r ./allure-results/api/* ./allure-merged/ 2>/dev/null || true
          cp -r ./allure-results/ui/*/* ./allure-merged/ 2>/dev/null || true

      - name: Install Allure CLI
        if: steps.check.outputs.has_results == 'true'
        run: |
          curl -sL https://github.com/allure-framework/allure2/releases/latest/download/allure-2.29.0.tgz \
            | sudo tar -xz -C /opt/
          echo "/opt/allure-2.29.0/bin" >> $GITHUB_PATH

      - name: Generate Allure site
        if: steps.check.outputs.has_results == 'true'
        run: allure generate ./allure-merged -o ./allure-report --clean

      - name: Upload Pages artifact
        if: steps.check.outputs.has_results == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./allure-report

      - name: Deploy to GitHub Pages
        if: steps.check.outputs.has_results == 'true'
        uses: actions/deploy-pages@v4

      - name: Skip publish (no results)
        if: steps.check.outputs.has_results != 'true'
        run: echo "No Allure results found. Skipping publish."
