name: Test Producer
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      run_ui:
        description: 'Run UI suite'
        type: boolean
        default: true
      run_api:
        description: 'Run API suite'
        type: boolean
        default: true
      browsers:
        description: 'UI browsers (comma-separated: chromium,firefox,webkit)'
        type: string
        default: 'chromium'

permissions:
  contents: write

jobs:
  ui:
    if: ${{ (github.event_name == 'workflow_dispatch' && inputs.run_ui) || (github.event_name != 'workflow_dispatch') }}
    uses: ./.github/workflows/ui-test.yml
    with:
      browsers:  ${{ github.event_name == 'workflow_dispatch' && inputs.browsers || 'chromium' }}
    secrets:
      CREDENTIALS: ${{ secrets.CREDENTIALS }}

  api:
    if: ${{ (github.event_name == 'workflow_dispatch' && inputs.run_api) || (github.event_name != 'workflow_dispatch') }}
    uses: ./.github/workflows/api-test.yml


  report-builder:
    runs-on: ubuntu-latest
    needs: [ui, api]
    if: ${{ !cancelled() }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: allure-*
          path: ./allure-results
          merge-multiple: true
        continue-on-error: true

      - name: Load test report history
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      
      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-results
          keep_reports: 10
      
      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          allow_empty_commit: true
      
      - name: Add report URL to summary
        run: |
          echo "## 📊 Test Report Summary" >> $GITHUB_STEP_SUMMARY
          echo "- UI status: **${{ needs.ui.result }}** | API status: **${{ needs.api.result }}**" >> $GITHUB_STEP_SUMMARY
          echo "- Report URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/" >> $GITHUB_STEP_SUMMARY
