name: UI Tests

on:
  workflow_call:
    inputs:
      base_url:
        required: false
        type: string
        default: ""
      browsers:
        required: false
        type: string
        default: "chromium" # e.g., "chromium,firefox,webkit"
    secrets:
      CREDENTIALS:
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      browsers_json: ${{ steps.mk.outputs.browsers_json }}
    steps:
      - id: mk
        run: |
          echo "browsers_json=[$(echo "${{ inputs.browsers }}" | sed 's/,/","/g' | sed 's/^/"/' | sed 's/$/"/' )]" >> $GITHUB_OUTPUT

  ui:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        browser: ${{ fromJson(needs.prepare.outputs.browsers_json) }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-ui-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-ui-

      - name: Install deps
        run: |
          pip install -r requirements.txt
          python -m playwright install --with-deps ${{ matrix.browser }}

      - name: Setup auth session
        shell: bash
        run: |
          echo "${{ secrets.CREDENTIALS }}" > .env
          python -m utils.setup_session

      - name: Run UI tests (${{ matrix.browser }})
        run: |
          pytest tests/web \
            --browser ${{ matrix.browser }} \
            --base-url=${{ inputs.base_url }} \
            -n=auto --reruns 1 --reruns-delay 2 \
            --alluredir=allure-results --headless --platform=all

      - name: Upload Allure (UI-${{ matrix.browser }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-ui-${{ matrix.browser }}
          path: allure-results
          if-no-files-found: warn

      - name: Cleanup authentication session
        if: always()
        run: |
          [ -d ".auth" ] && rm -rf .auth
